### ISSUE TITLE
Change the heading of the comment from Deployment to Plan?

### ISSUE THREAD

**Issue by simonblake-mp** [borchero/terraform-plan-comment#8]
Hey, love the action.  

One cosmetic request, could the text that is used for the header message - ie

"Terraform Deployment - $id"

either be made configurable, or changed to something like

"Terraform Plan - $id"

"Deployment" implies (to me at least) a change already done, whereas the comment created by this action is for a proposed change that might happen in the future.  I suspect many users of this action are following up after apply with additional comments in the PR that contain the results of the apply run, so it would be nice to clearly distinguish between the plans and the applies?

**Comment by borchero** [comment]
Good point! Thanks for bringing it up :)
